[package]
name = "hgi"
version = "0.1.0"
authors = ["pl0q1n <pl0q1n@gmail.com>"]

[dependencies]
image = "0.19.0"
serde = "1.0.68"
clap = "2.32.0"
bit-vec = "0.5.0"
serde_derive = "1.0.73"
bincode = "1.0.1"
byteorder = "1.2.4"
flate2 = "1.0.2"

[profile.release]
lto = true